---
- name: Assertions and Setup Connections
  gather_facts: false
  vars_files: 
    - group_vars/secrets.yml
  hosts: all
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - name: Set Connection Parameters
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ F5_USER }}"
          password: "{{ F5_PASSWORD }}"
          validate_certs: false
          timeout: 120
      no_log: true

    - name: Create pool
      f5networks.f5_modules.bigip_pool:
        provider: "{{ provider }}"
        lb_method: "round-robin"
        monitors: http
        monitor_type: "and_list"
        name: "pool1"

    - name: Add nodes to pool
      f5networks.f5_modules.bigip_pool_member:
        provider: "{{ provider }}"
        host: "{{ item.host }}"
        name: "{{ item.host }}"
        pool: "pool1"
        port: "80"
      loop:
      - host: "10.10.10.10"
      - host: "10.10.10.11"
      - host: "10.10.10.12"
...