---
- name: Assertions and Setup Connections
  gather_facts: false
  vars_files: 
    - group_vars/secrets.yml
  hosts: all
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - name: Set Connection Parameters
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ F5_USER }}"
          password: "{{ F5_PASSWORD }}"
          validate_certs: false
          timeout: 120
      no_log: true

    - name: Create an ICMP monitor
      bigip_monitor_icmp:
        name: icmp1
        adaptive: no
        interval: 1
        time_until_up: 0
        timeout: 3
        provider:
          password: secret
          server: lb.mydomain.com
          user: admin
      delegate_to: localhost
...