---
- name: Assertions and Setup Connections
  gather_facts: false
  vars_files: 
    - group_vars/secrets.yml
  hosts: all
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - name: Set Connection Parameters
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ F5_USER }}"
          password: "{{ F5_PASSWORD }}"
          validate_certs: false
          timeout: 120
      no_log: true

    - name: Create HTTP Monitor
      bigip_monitor_http:
        state: present
        ip: 10.10.10.10
        name: my_http_monitor
        provider:
          server: lb.mydomain.com
          user: admin
          password: secret
      delegate_to: localhost
...