---
- name: F5 App Delete
  gather_facts: false
  vars_files:
    - group_vars/secrets.yml
  hosts: all
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - set_fact:
       provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USER }}"
        password: "{{ F5_PASSWORD }}"
        server_port: 443
        validate_certs: false

    - name: DELETE VIRTUAL SERVER
      f5networks.f5_modules.bigip_virtual_server:
        provider: "{{provider}}"
        name: "vip1"
        state: absent

    - name: DELETE POOL
      f5networks.f5_modules.bigip_pool:
        provider: "{{provider}}"
        name: "pool1"
        state: absent

    - name: DELETE NODES
      f5networks.f5_modules.bigip_node:
        provider: "{{provider}}"
        name: "{{ item.host }}"
        state: absent
      loop:
        - host: "10.10.10.10"
        - host: "10.10.10.11"
        - host: "10.10.10.12"
...
