---
- name: Assertions and Setup Connections
  gather_facts: false
  vars_files: 
    - group_vars/secrets.yml
  hosts: bigip_ha
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - name: Set Connection Parameters
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ F5_USER }}"
          password: "{{ F5_PASSWORD }}"
          validate_certs: false
          timeout: 120
      no_log: true

    - name: Test Connection to BIG-IP
      bigip_wait:
        timeout: 60
        provider: "{{ provider }}"
      no_log: true
      delegate_to: localhost

    - name: Get REST Authentication Token
      uri:
        url: "https://{{ ansible_host }}/mgmt/shared/authn/login"
        method: POST
        body_format: json
        body:
          username: "{{ F5_USER }}"
          password: "{{ F5_PASSWORD }}"
          loginProviderName: tmos
        status_code: 200
        validate_certs: false
      no_log: true
      register: auth_response
      delegate_to: localhost

##################################################################

    - name: Add the iRule contained in static file irule1 to the lTM module
      f5networks.f5_modules.bigip_irule:
        module: ltm
        name: iRule1
        src: irules/irule1
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Add the iRule contained in static file irule2 to the LTM module
      f5networks.f5_modules.bigip_irule:
        module: ltm
        name: iRule2
        src: irules/irule2
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Create Wide IP "a" record
      f5networks.f5_modules.bigip_gtm_wide_ip:
        description:
        pool_lb_method: round-robin
        name: my-wide-ip.example.com
        type: a
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Create Wide IP "aaaa" record
      f5networks.f5_modules.bigip_gtm_wide_ip:
        pool_lb_method: round-robin
        name: my-wide-ip.example.com
        type: aaaa
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Add iRules to the Wide IP
      f5networks.f5_modules.bigip_gtm_wide_ip:
        pool_lb_method: round-robin
        name: my-wide-ip.example.com
        type: a
        irules:
          - GTM_iRule1
          # - iRule2
        provider: "{{ provider }}"
      delegate_to: localhost

    # - name: Assign a pool with ratio to the Wide IP
    #   f5networks.f5_modules.bigip_gtm_wide_ip:
    #     pool_lb_method: round-robin
    #     name: my-wide-ip.example.com
    #     type: a
    #     pools:
    #       - name: pool1
    #         ratio: 100
    #         order: 2
    #       - name: pool1
    #         ratio: 100
    #         order: 1
    #     provider: "{{ provider }}"
    #     # server: "{{ ansible_host }}"
    #   delegate_to: localhost

    # - name: Assign a pool with persistence to the Wide IP
    #   f5networks.f5_modules.bigip_gtm_wide_ip:
    #     pool_lb_method: round-robin
    #     name: my-wide-ip.example.com
    #     type: a
    #     pools:
    #       - name: pool1
    #         persistence: yes
    #         persist_cidr_ipv4: 24
    #         persist_cidr_ipv6: 120
    #         persistence_ttl: 3500
    #     provider: "{{ provider }}"
    #     # server: "{{ ansible_host }}"
    #   delegate_to: localhost
...
