---
- name: Assertions and Setup Connections
  gather_facts: false
  vars_files: 
    - group_vars/secrets.yml
  hosts: bigip_ha
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - name: Set Connection Parameters
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ F5_USER }}"
          password: "{{ F5_PASSWORD }}"
          validate_certs: false
          timeout: 120
      no_log: true

    - name: Test Connection to BIG-IP
      bigip_wait:
        timeout: 60
        provider: "{{ provider }}"
      no_log: true
      delegate_to: localhost

    - name: Get REST Authentication Token
      uri:
        url: "https://{{ ansible_host }}/mgmt/shared/authn/login"
        method: POST
        body_format: json
        body:
          username: "{{ F5_USER }}"
          password: "{{ F5_PASSWORD }}"
          loginProviderName: tmos
        status_code: 200
        validate_certs: false
      no_log: true
      register: auth_response
      delegate_to: localhost

##################################################################

    - name: Add the iRule contained in static file irule1 to the GTM module
      f5networks.f5_modules.bigip_irule:
        module: gtm
        name: GTM_iRule1
        src: irules/gtm_irule1
        state: absent
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Add the iRule contained in static file irule2 to the LTM module
      f5networks.f5_modules.bigip_irule:
        module: ltm
        name: GTM_iRule2
        src: irules/gtm_irule2
        state: absent
        provider: "{{ provider }}"
      delegate_to: localhost
...
