---
- name: Big-IP Info
  gather_facts: false
  hosts: all
  vars_files:
    - group_vars/secrets.yml
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - set_fact:
       provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USER }}"
        password: "{{ F5_PASSWORD }}"
        server_port: 22
        transport: cli
        validate_certs: false

    - name: List GTM HTTP Monitors
      bigip_command:
        commands:
        - tmsh list gtm monitor | grep 'gtm monitor http ' | awk '{print $4}'
        provider: "{{ provider }}"
      register: http_monitor
      delegate_to: localhost

    -  debug:
        var: http_monitor.stdout_lines

- name: Big-IP Info
  gather_facts: false
  hosts: all
  vars_files:
    - group_vars/secrets.yml
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - set_fact:
       provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USER }}"
        password: "{{ F5_PASSWORD }}"
        server_port: 443
        validate_certs: false

    - name: List GTM HTTP Monitors
      bigip_command:
        commands:
        - tmsh modify gtm monitor http stupid_nm ignore_down_response enabled
        provider: "{{ provider }}"
      register: result
      delegate_to: localhost

    -  debug:
        var: result.stdout_lines

    # - name: Modify a GTM HTTP monitor
    #   bigip_gtm_monitor_http:
    #     name: "{{ item }}"
    #     ignore_down_response: true
    #     state: present
    #     provider: "{{ provider }}"
    #   delegate_to: localhost
    #   with_items: "{{ http_monitor.stdout_lines }}"
...