---
- name: Big-IP Info
  gather_facts: false
  hosts: all
  vars_files:
    - group_vars/secrets.yml
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - set_fact:
       provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USER }}"
        password: "{{ F5_PASSWORD }}"
        server_port: 22
        transport: cli
        validate_certs: false

    - name: List GTM HTTPS Monitors
      bigip_command:
        commands:
        - tmsh list gtm monitor | grep 'gtm monitor https' | awk '{print $4}'
        provider: "{{ provider }}"
      register: https_monitor
      delegate_to: localhost

    -  debug:
        var: https_monitor.stdout_lines

    - name: Debug to show each line
      ansible.builtin.debug:
        msg: "item {{ https_monitor.stdout_lines }}"

- name: Big-IP Info
  gather_facts: false
  hosts: all
  vars_files:
    - group_vars/secrets.yml
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - set_fact:
       provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USER }}"
        password: "{{ F5_PASSWORD }}"
        server_port: 443
        validate_certs: false

    - name: Modify a GTM HTTPS monitor
      bigip_gtm_monitor_https:
        name: "{{ item }}"
        ignore_down_response: true
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost
      with_items: "{{ https_monitor.stdout_lines }}"
...