---
- name: Assertions and Setup Connections
  gather_facts: false
  vars_files: 
    - group_vars/secrets.yml
  hosts: bigip_ha
  collections:
    - f5networks.f5_modules

  tasks:
    - name: Set Connection Parameters
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ F5_USER }}"
          password: "{{ F5_PASSWORD }}"
          validate_certs: false
          timeout: 120
      no_log: true

    - name: Test Connection to BIG-IP
      bigip_wait:
        timeout: 60
        provider: "{{ provider }}"
      no_log: true
      delegate_to: localhost

    - name: Collect Facts
      bigip_device_info:
        gather_subset:
          - self-ips
        provider: "{{ provider }}"
      delegate_to: localhost
      register: result

    - name: Display Self-IPs
      debug:
        var: result.stdout_lines
...