---
- name: Assertions and Setup Connections
  gather_facts: false
  vars_files:
    - group_vars/secrets.yml
  hosts: bigip_ha
  connection: ssh
  collections:
    - f5networks.f5_modules

  tasks:
    - name: Set Connection Parameters
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ F5_USER }}"
          password: "{{ F5_PASSWORD }}"
          validate_certs: false
          timeout: 120
      no_log: true

    - name: Test Connection to BIG-IP
      bigip_wait:
        timeout: 60
        provider: "{{ provider }}"
      no_log: true
      delegate_to: localhost

    - name: List Vlan-Groups Command
      bigip_command:
        commands:
          - list net vlan-group mode
        provider: "{{ provider }}"
        register: results
      delegate_to: localhost

    - debug: msg="{{inventory_hostname}} {{results}}"

    # - set_fact:
    #     vlan_group: "{{vlan_group|default([]) + [item['name']] }}"
    #   with_items: "{{ vlan_group_response['json']['items'] }}"

    - debug:
        var: results
...
