---
- name: Get Big-IP software status
  gather_facts: false
  vars_files:
    - group_vars/secrets.yml
  hosts: all
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - set_fact:
       provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USER }}"
        password: "{{ F5_PASSWORD }}"
        server_port: 443
        validate_certs: false

    - name: Get software status
      bigip_command:
        commands:
          - show sys software status
        provider: "{{ provider }}"
      register: result
      delegate_to: localhost

    - name: Display Software Status
      debug:
        var: result
...