---
- name: Assertions and Setup Connections
  gather_facts: false
  vars_files: 
    - group_vars/secrets.yml
  hosts: all
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - set_fact:
       provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USER }}"
        password: "{{ F5_PASSWORD }}"
        # server_port: 22
        # transport: cli
        server_port: 443
        validate_certs: false

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: files/f5-appsvcs-3.42.0-5.noarch.rpm
        dest: /var/config/rest/downloads/
        owner: root
        group: root
        mode: '0777'
      register: as3_rpm

    # - name: SCP RPM Package
    #   bigip_command:
    #     commands:
    #     - scp -p files/f5-appsvcs-3.42.0-5.noarch.rpm /var/config/rest/downloads/
    #     provider: "{{ provider }}"
    #   register: as3_rpm
    #   delegate_to: localhost

    -  debug:
        var: as3_rpm.stdout_lines

    # - name: Install AS3 and don't delete package file
    #   bigip_lx_package:
    #     package: f5-appsvcs-3.42.0-5.noarch.rpm
    #     state: present
    #     retain_package_file: true
    #     provider: "{{ provider }}"
    #   delegate_to: localhost
...