---
- name: Modify DB Variable
  gather_facts: no
  vars_files: 
    - group_vars/secrets.yml
  hosts: all
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - set_fact:
       provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USER }}"
        password: "{{ F5_PASSWORD }}"
        server_port: 443
        validate_certs: no
        auth_provider: tmos

    - name: Modify DB Variable
      bigip_sys_db:
        provider: "{{ provider }}"
        key: httpd.matchclient
        value: false
      delegate_to: localhost

    - name: Save Configuration
      bigip_config:
        save: yes
        provider: "{{ provider }}"
      delegate_to: localhost
...