---
- name: Creat new user
  gather_facts: false
  vars_files: 
    - group_vars/secrets.yml
  hosts: all
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - set_fact:
       provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USER }}"
        password: "{{ F5_PASSWORD }}"
        server_port: 443
        validate_certs: false

    - name: Add user with Auditor role
      bigip_user:
        name: FXS_microseg-f5-api
        state: absent
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Save the running configuration of the BIG-IP
      bigip_config:
        save: yes
        provider: "{{ provider }}"
      delegate_to: localhost
...