---
- name: Big-IP Info
  gather_facts: false
  hosts: all
  vars_files:
    - group_vars/secrets.yml
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - set_fact:
       provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USER }}"
        password: "{{ F5_PASSWORD }}"
        server_port: 443
        validate_certs: false

    - name: Restart HTTPD Daemon
      bigip_command:
        commands:
          - bigstart restart httpd
        provider: "{{ provider }}"
      register: result
      delegate_to: localhost
...